# Generated by Django 5.2.3 on 2025-06-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('send_email', 'Send Email'), ('process_image', 'Process Image'), ('generate_report', 'Generate Report'), ('backup_database', 'Backup Database'), ('fetch_data', 'Fetch Data'), ('batch_process', 'Batch Process'), ('send_notification', 'Send Notification'), ('cleanup_files', 'Cleanup Files')], max_length=50)),
                ('parameters', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('max_retries', models.IntegerField(default=3)),
                ('retries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
