# Generated by Django 5.2.3 on 2025-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='schedule_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Every Hour'), ('daily', 'Every Day'), ('monthly', 'Every Month'), ('yearly', 'Every Year')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('send_email', 'Send Email'), ('process_image', 'Process Image'), ('generate_report', 'Generate Report'), ('backup_database', 'Backup Database'), ('fetch_data', 'Fetch Data'), ('batch_process', 'Batch Process'), ('send_notification', 'Send Notification'), ('cleanup_files', 'Cleanup Files'), ('upload_file', 'Upload File to S3')], max_length=50),
        ),
    ]
