# Generated by Django 5.2.3 on 2025-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_schedule_type_job_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='schedule_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='immediate', max_length=20),
        ),
    ]
