# Generated by Django 5.2.3 on 2025-06-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly')], default='daily', max_length=20, null=True),
        ),
    ]
