# Generated by Django 5.2.3 on 2025-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly')], default='daily', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('interval', 'Interval')], default='immediate', max_length=20),
        ),
    ]
